name: widgets
description: Widgets and utilities.
version: 0.0.1
homepage: https://github.com/alefnula/widgets

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  tray_manager: ^0.1.5
  window_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
